In [18]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cluster import KMeans
from scipy.spatial import distance


In [19]:
data=pd.read_csv('./anime.csv')

In [20]:
data=data[data['genre']!='Hentai']

In [21]:
data.head()

anime_id                              name  \
0     32281                    Kimi no Na wa.   
1      5114  Fullmetal Alchemist: Brotherhood   
2     28977                          Gintama°   
3      9253                       Steins;Gate   
4      9969                     Gintama&#039;   

                                               genre   type episodes  rating  \
0               Drama, Romance, School, Supernatural  Movie        1    9.37   
1  Action, Adventure, Drama, Fantasy, Magic, Mili...     TV       64    9.26   
2  Action, Comedy, Historical, Parody, Samurai, S...     TV       51    9.25   
3                                   Sci-Fi, Thriller     TV       24    9.17   
4  Action, Comedy, Historical, Parody, Samurai, S...     TV       51    9.16   

   members  
0   200630  
1   793665  
2   114262  
3   673572  
4   151266

In [22]:
#Let's make our own algorithm for the dataset

In [23]:
# So we are gonna make an anime recommendation system on our own :)

In [24]:
# we want to know all the genres of the animes

In [25]:
genre=data['genre'].values
print(genre)

['Drama, Romance, School, Supernatural'
 'Action, Adventure, Drama, Fantasy, Magic, Military, Shounen'
 'Action, Comedy, Historical, Parody, Samurai, Sci-Fi, Shounen' ...
 'Comedy, Hentai' 'Hentai, Slice of Life' 'Demons, Hentai, Supernatural']


In [26]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 11471 entries, 0 to 12285
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   anime_id  11471 non-null  int64  
 1   name      11471 non-null  object 
 2   genre     11409 non-null  object 
 3   type      11446 non-null  object 
 4   episodes  11471 non-null  object 
 5   rating    11248 non-null  float64
 6   members   11471 non-null  int64  
dtypes: float64(1), int64(2), object(4)
memory usage: 716.9+ KB


In [27]:
lis=[]
for i in genre:
    i=str(i)
    for p in i.split(','):
        if p not in lis:
            lis.append(p)

In [28]:
sorted_list=sorted(lis)
print(sorted_list)

[' Adventure', ' Cars', ' Comedy', ' Dementia', ' Demons', ' Drama', ' Ecchi', ' Fantasy', ' Game', ' Harem', ' Hentai', ' Historical', ' Horror', ' Josei', ' Kids', ' Magic', ' Martial Arts', ' Mecha', ' Military', ' Music', ' Mystery', ' Parody', ' Police', ' Psychological', ' Romance', ' Samurai', ' School', ' Sci-Fi', ' Seinen', ' Shoujo', ' Shoujo Ai', ' Shounen', ' Shounen Ai', ' Slice of Life', ' Space', ' Sports', ' Super Power', ' Supernatural', ' Thriller', ' Vampire', ' Yaoi', ' Yuri', 'Action', 'Adventure', 'Cars', 'Comedy', 'Dementia', 'Demons', 'Drama', 'Ecchi', 'Fantasy', 'Game', 'Harem', 'Hentai', 'Historical', 'Horror', 'Josei', 'Kids', 'Magic', 'Martial Arts', 'Mecha', 'Military', 'Music', 'Mystery', 'Parody', 'Police', 'Psychological', 'Romance', 'Samurai', 'School', 'Sci-Fi', 'Seinen', 'Shoujo', 'Shounen', 'Slice of Life', 'Space', 'Sports', 'Super Power', 'Supernatural', 'Thriller', 'Vampire', 'Yaoi', 'nan']


In [29]:
dic={}


In [30]:
t=[]
for i in genre:
    for j in lis:
        dic[j]=0
    i=str(i)
    for p in i.split(','):
        dic[p]+=1
    t.append(list(dic.values()))
        

In [31]:
len(t)

11471

In [32]:
X=np.array(t)
print(X)

[[1 1 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]]


In [33]:
# Dynamic Recommendation System made by me

In [34]:
# input 1 is the anime name
# input 2 is the number of search result you want
s=input('Enter the anime you like and we will find more like those for you  :')
num=int(input('Please enter the number of recommendations you want:'))
name=data['name'].values
for i in range(len(name)):
    name[i]=name[i].lower()
s=s.lower()
h=-1
for i in range(len(name)):
    if s in name[i]:
        h=i
        break
imp=[]
if h==-1:
    print('Sorry No match found :(')
else:
    for i in range(len(t)):
        if i==h:
            continue
        else:
            if len(imp)<num:
                imp.append([distance.euclidean(t[i], t[h]),t[i],i])
            else:
                imp.sort()
                if imp[num-1][0]>distance.euclidean(t[i],t[h]):
                    del imp[num-1]
                    imp.append([distance.euclidean(t[i],t[h]),t[i],i])
    name=data['name'].values
    print('The anime recommended for you are :')
    count=0
    for i in imp:
        count+=1
        print(count,'. ',name[i[2]])
                

The anime recommended for you are :
1 .  bleach movie 4: jigoku-hen
2 .  bleach movie 3: fade to black - kimi no na wo yobu
