In [1]:
import numpy as np
import pandas as pd

In [3]:
X = np.zeros((3,4))
print(X)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
X = np.full((2,3), 5)
X

array([[5, 5, 5],
       [5, 5, 5]])

In [9]:
X = np.eye(5,dtype=np.int64)
X

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int64)

In [10]:
y = np.linspace(0,50,10, endpoint=False).reshape(5,2)
y

array([[ 0.,  5.],
       [10., 15.],
       [20., 25.],
       [30., 35.],
       [40., 45.]])

In [16]:
X = np.arange(20).reshape(4, 5)
print(X)
# select all the elements that are in the 2nd through 4th rows and in the 3rd to 5th columns
Z = X[:,1:5]
Z

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14],
       [16, 17, 18, 19]])

In [19]:
x = np.array([1, 2, 3, 4, 5])
# delete the first and fifth element of x
print(x)
x = np.delete(x, [0,4])
x

[1 2 3 4 5]


array([2, 3, 4])

In [1]:
l='mathematics'
print(l[8:11])

ics


In [3]:
print(l[slice(8,11,1)])

ics
