In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
df= pd.read_csv('../Top3000_imdb_indian_movies.csv')
df.head()

Title  Date_of_Release                                 Genre  \
0          3 Idiots             2009             Comedy, Drama               
1  Taare Zameen Par             2007             Drama, Family               
2                PK             2014    Comedy, Drama, Musical               
3             Radhe             2021   Action, Crime, Thriller               
4            Dangal             2016  Action, Biography, Drama               

                    Crew_dir  \
0            Rajkumar Hirani   
1  s:Aamir Khan, Amole Gupte   
2            Rajkumar Hirani   
3                Prabhu Deva   
4              Nitesh Tiwari   

                                          Cast_stars  \
0    Aamir Khan, Madhavan, Mona Singh, Sharman Joshi   
1  Darsheel Safary, Aamir Khan, Tisca Chopra, Vip...   
2  Aamir Khan, Anushka Sharma, Sanjay Dutt, Boman...   
3  Salman Khan, Disha Patani, Randeep Hooda, Jack...   
4  Aamir Khan, Sakshi Tanwar, Fatima Sana Shaikh,...   

                                        Plot_summary  Age_of_content   Votes  \
0  Two friends are searching for their long lost ...              12  366038   
1  An eight-year-old boy is thought to be a lazy ...              14  179838   
2  An alien on Earth loses the only device he can...               7  171776   
3  After taking the dreaded gangster Gani Bhai, A...               0  171349   
4  Former wrestler Mahavir Singh Phogat and his t...               5  170210   

   ImDBRating  
0         8.4  
1         8.4  
2         8.1  
3         1.8  
4         8.4

In [3]:
df.tail()

Title  Date_of_Release                             Genre  \
2994      Waqt Ki Awaz             1988  Action, Crime, Drama               
2995            Ilzaam             1986         Drama, Family               
2996  Jheel Ke Us Paar             1973        Drama, Romance               
2997   Ashad Ka Ek Din             1971      Biography, Drama               
2998  Around the World             1967       Comedy, Romance               

          Crew_dir                                         Cast_stars  \
2994    K. Bapaiah  Vikas Anand, Asrani, Mithun Chakraborty, Moush...   
2995   Shibu Mitra  Shashi Kapoor, Shatrughan Sinha, Raj Kiran, An...   
2996  Bhappi Sonie       Dharmendra, Mumtaz, Prem Chopra, Mehmood Jr.   
2997     Mani Kaul  Aruna Irani, Arun Khopkar, Rekha Sabnis, Om Sh...   
2998        Pachhi              Raj Kapoor, Rajshree, Ameeta, Mehmood   

                                           Plot_summary  Age_of_content  \
2994  Wealthy Lata I. Prasad refuses to obey her wid...              33   
2995  Ajay is a street dancer and while people are w...              35   
2996  Kulwant Rai's horse carriage runs over a child...              48   
2997  Aashad Ka Ek Din is an adaptation of the play ...              50   
2998  Raj Singh is the nephew and heir apparent of m...              54   

      Votes  ImDBRating  
2994    105         6.3  
2995    105         5.9  
2996    105         7.2  
2997    105         7.4  
2998    105         6.2

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2999 entries, 0 to 2998
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Title            2999 non-null   object 
 1   Date_of_Release  2999 non-null   int64  
 2   Genre            2999 non-null   object 
 3   Crew_dir         2994 non-null   object 
 4   Cast_stars       2999 non-null   object 
 5   Plot_summary     2999 non-null   object 
 6   Age_of_content   2999 non-null   int64  
 7   Votes            2999 non-null   int64  
 8   ImDBRating       2999 non-null   float64
dtypes: float64(1), int64(3), object(5)
memory usage: 211.0+ KB


In [5]:
genre=df['Genre'].values
genre

array(['Comedy, Drama            ', 'Drama, Family            ',
       'Comedy, Drama, Musical            ', ...,
       'Drama, Romance            ', 'Biography, Drama            ',
       'Comedy, Romance            '], dtype=object)

In [6]:
types=[]
for i in genre:
    for j in i.split(','):
        if j.strip() not in types:
            types.append(j.strip())
print(types,len(types))

['Comedy', 'Drama', 'Family', 'Musical', 'Action', 'Crime', 'Thriller', 'Biography', 'Romance', 'Sport', 'Music', 'Adventure', 'Mystery', 'History', 'Horror', 'Fantasy', 'War', 'Sci-Fi', 'Animation', 'Western', '****'] 21


In [7]:
dic={}
target=[]
for i in genre:
    for j in types:
        dic[j]=0
    i=str(i)
    for p in i.split(','):
        p=p.strip()
        dic[p]+=1
    target.append(list(dic.values()))
print(len(target),len(target[0]))

2999 21


In [8]:
X=np.array(target)
print(X)

[[1 1 0 ... 0 0 0]
 [0 1 1 ... 0 0 0]
 [1 1 0 ... 0 0 0]
 ...
 [0 1 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]]


In [9]:
from scipy.spatial import distance
def finder(name,count):
    title=df['Title'].values
    title=[i.lower() for i in title]
    counter=-1
    for i in range(len(title)):
        if name in title[i]:
            counter=i
            break
    rec=[]
    if counter==-1:
        print("No recommendations found")
        return None
    else:
        for i in range(len(target)):
            if counter==i:
                continue
            else:
                if len(rec)<count:
                    rec.append([distance.euclidean(target[i], target[counter]),target[i],i])
                else:
                    rec.sort()
                    if distance.euclidean(target[i], target[counter])<rec[-1][0]:
                        rec[-1]=[distance.euclidean(target[i], target[counter]),target[i],i]
    names=df['Title'].values
    rec_names=[names[i] for i in [i[2] for i in rec]]
    return rec_names

In [16]:
ans=finder(input("Enter a movie name: ").lower(),int(input("Enter the number of recommendations: ")))
if ans:
    for i in ans:
        print('Title: '+str(i)+' | Release Year: '+str(df[df['Title']==i]['Date_of_Release'].values[0])+' | Ratings: '+str(df[df['Title']==i]['ImDBRating'].values[0]))

Title: Barfi! | Release Year: 2012 | Ratings: 8.1
Title: Dil Chahta Hai | Release Year: 2001 | Ratings: 8.1
Title: Jab We Met | Release Year: 2007 | Ratings: 7.9
Title: Lage Raho Munna Bhai | Release Year: 2006 | Ratings: 8.0
Title: Chhichhore | Release Year: 2019 | Ratings: 8.3
Title: Wake Up Sid | Release Year: 2009 | Ratings: 7.6
Title: Dev.D | Release Year: 2009 | Ratings: 8.0
Title: Tanu Weds Manu Returns | Release Year: 2015 | Ratings: 7.6
Title: Jaane Tu... Ya Jaane Na | Release Year: 2008 | Ratings: 7.5
Title: Zero | Release Year: 2018 | Ratings: 5.4
